# -*- coding: utf-8 -*-
"""privacy-aware location system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-gTo6jHMc7PgqPPbNVd2cHZ5Yhqot483
"""

!pip install geopy folium matplotlib scipy cryptography

"""import statements"""

import math
import random
import numpy as np
import folium
import matplotlib.pyplot as plt
from geopy.distance import geodesic
import requests
from scipy.spatial import Voronoi, voronoi_plot_2d
from cryptography.fernet import Fernet

"""function to generate cloaked area using haversine"""

def haversine(lat1, lon1, lat2, lon2):
    # Haversine formula to calculate distance between two points
    R = 6371  # Radius of the Earth in kilometers
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = math.sin(dlat / 2) * math.sin(dlat / 2) + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon / 2) * math.sin(dlon / 2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    distance = R * c
    return distance

def generate_cloaked_area_haversine(actual_location, radius):
    # Generate a random point within the radius using haversine formula
    R = 6371  # Radius of the Earth in kilometers
    angle = random.uniform(0, 2 * math.pi)
    distance = random.uniform(0, radius)
    lat1 = math.radians(actual_location[0])
    lon1 = math.radians(actual_location[1])
    lat2 = math.asin(math.sin(lat1) * math.cos(distance / R) + math.cos(lat1) * math.sin(distance / R) * math.cos(angle))
    lon2 = lon1 + math.atan2(math.sin(angle) * math.sin(distance / R) * math.cos(lat1), math.cos(distance / R) - math.sin(lat1) * math.sin(lat2))
    cloaked_location = (math.degrees(lat2), math.degrees(lon2))
    return cloaked_location

"""function to generate k-anonymous cloaked area using density-based clustering"""

def density_based_cloaking(user_locations, k, radius):
    from sklearn.cluster import DBSCAN

    # Convert locations to numpy array
    locations = np.array(user_locations)

    # Use DBSCAN for density-based clustering
    db = DBSCAN(eps=radius / 111320, min_samples=k).fit(locations)
    labels = db.labels_

    # Ensure each cluster has at least k users
    cloaked_areas = []
    for label in set(labels):
        if label == -1:
            continue  # Skip noise points
        cluster = locations[labels == label]
        if len(cluster) >= k:
            center = cluster.mean(axis=0)
            cloaked_location = generate_cloaked_area_haversine(center, radius)
            cloaked_areas.append(cloaked_location)

    return cloaked_areas

"""function to estimate population density using local data"""

def estimate_population_density(location, population_data):
    # Example: Estimate population density using local data (e.g., census data)
    # population_data should be a dictionary with (lat, lon) as keys and population density as values
    return population_data.get(location, 1000)  # Default to 1000 if no data available

def adaptive_k_anonymity(user_locations, base_k, radius, population_data):
    # Adjust k based on local population density
    clusters = []
    for location in user_locations:
        density = estimate_population_density(location, population_data)
        k = base_k + (density // 1000)  # Example: increase k by 1 for every 1000 people per sq km
        added = False
        for cluster in clusters:
            if len(cluster) < k:
                cluster.append(location)
                added = True
                break
        if not added:
            clusters.append([location])

    # Generate a cloaked area for each cluster
    cloaked_areas = []
    for cluster in clusters:
        center = (sum(loc[0] for loc in cluster) / len(cluster), sum(loc[1] for loc in cluster) / len(cluster))
        cloaked_location = generate_cloaked_area_haversine(center, radius)
        cloaked_areas.append(cloaked_location)

    return cloaked_areas

"""function to generate k-anonymous cloaked area using Voronoi"""

def voronoi_cloaking(user_locations, k):
    # Generate Voronoi diagram
    vor = Voronoi(user_locations)

    # Group users into clusters based on Voronoi cells
    clusters = []
    for region_index in range(len(vor.point_region)):
        cluster = []
        for point_index in range(len(vor.point_region)):
            if vor.point_region[point_index] == region_index:
                cluster.append(user_locations[point_index])
        clusters.append(cluster)

    # Ensure each cluster has at least k users
    cloaked_areas = []
    for cluster in clusters:
        if len(cluster) >= k:
            center = (sum(loc[0] for loc in cluster) / len(cluster), sum(loc[1] for loc in cluster) / len(cluster))
            cloaked_location = generate_cloaked_area_haversine(center, 0.5)  # 500 meters radius
            cloaked_areas.append(cloaked_location)

    return cloaked_areas

"""function to get population density using API"""

def get_population_density_api(location):
    # Example API call to get population density (replace with actual API)
    api_url = f"https://api.example.com/population_density?lat={location[0]}&lon={location[1]}"
    response = requests.get(api_url)
    if response.status_code == 200:
        data = response.json()
        return data['density']
    else:
        return 1000  # Default value if API fails

def adaptive_k_anonymity_api(user_locations, base_k, radius):
    # Adjust k based on real-world population density
    clusters = []
    for location in user_locations:
        density = get_population_density_api(location)
        k = base_k + (density // 1000)  # Example: increase k by 1 for every 1000 people per sq km
        added = False
        for cluster in clusters:
            if len(cluster) < k:
                cluster.append(location)
                added = True
                break
        if not added:
            clusters.append([location])

    # Generate a cloaked area for each cluster
    cloaked_areas = []
    for cluster in clusters:
        center = (sum(loc[0] for loc in cluster) / len(cluster), sum(loc[1] for loc in cluster) / len(cluster))
        cloaked_location = generate_cloaked_area_haversine(center, radius)
        cloaked_areas.append(cloaked_location)

    return cloaked_areas

"""use folium to visualize cloaked area"""

def visualize_cloaked_area(actual_location, cloaked_location, radius):
    # Create a map centered around the actual location
    m = folium.Map(location=actual_location, zoom_start=15)

    # Add the actual location to the map
    folium.Marker(actual_location, popup="Actual Location", icon=folium.Icon(color="red")).add_to(m)

    # Add the cloaked location to the map
    folium.Marker(cloaked_location, popup="Cloaked Location", icon=folium.Icon(color="blue")).add_to(m)

    # Add a circle to represent the cloaked area
    folium.Circle(actual_location, radius=radius * 1000, color="blue", fill=True, fill_opacity=0.2).add_to(m)

    return m

"""use matplotlib to visualize the geofence"""

def visualize_geofence(user_location, geofence_center, geofence_radius):
    fig, ax = plt.subplots()

    # Plot the geofence center
    ax.plot(geofence_center[1], geofence_center[0], 'ro')
    ax.annotate("Geofence Center", (geofence_center[1], geofence_center[0]))

    # Plot the user location
    ax.plot(user_location[1], user_location[0], 'bo')
    ax.annotate("User Location", (user_location[1], user_location[0]))

    # Plot the geofence circle
    circle = plt.Circle((geofence_center[1], geofence_center[0]), geofence_radius / 111320, color='b', fill=False)
    ax.add_artist(circle)

    ax.set_xlim([geofence_center[1] - 0.02, geofence_center[1] + 0.02])
    ax.set_ylim([geofence_center[0] - 0.02, geofence_center[0] + 0.02])
    ax.set_aspect('equal')
    plt.xlabel('Longitude')
    plt.ylabel('Latitude')
    plt.title('Geofence Visualization')
    plt.grid(True)
    plt.show()

"""function to check if an user is within a geofence"""

def check_geofence(user_location, geofence_center, geofence_radius):
    distance = geodesic(user_location, geofence_center).meters
    return distance <= geofence_radius

def fuzzy_geofence(user_location, geofence_center, base_radius, user_privacy_level):
    # Adjust the geofence radius based on user privacy level and add fuzziness
    adjusted_radius = base_radius * user_privacy_level
    fuzziness = random.uniform(0.8, 1.2)  # Example fuzziness range
    return check_geofence(user_location, geofence_center, adjusted_radius * fuzziness)

"""function to add noise to location data using adaptive differential privacy"""

def adaptive_differential_privacy_noise(actual_location, sensitivity):
    # Adjust epsilon based on sensitivity
    epsilon = 1 / sensitivity
    scale = 1 / epsilon
    noise_x = np.random.laplace(0, scale)
    noise_y = np.random.laplace(0, scale)
    obfuscated_location = (actual_location[0] + noise_x, actual_location[1] + noise_y)
    return obfuscated_location

"""function to evaluate adversarial robustness"""

def evaluate_adversarial_robustness(actual_location, obfuscated_location):
    # Example: Evaluate robustness against location correlation attacks
    distance = geodesic(actual_location, obfuscated_location).meters
    if distance > 500:  # Example threshold
        return "Robust against correlation attacks"
    else:
        return "Vulnerable to correlation attacks"

"""function to fetch nearby services"""

def fetch_nearby_services(obfuscated_location, api_key):
    # Example: Fetch nearby services using Google Places API
    url = f"https://maps.googleapis.com/maps/api/place/nearbysearch/json?location={obfuscated_location[0]},{obfuscated_location[1]}&radius=1500&key={api_key}"
    response = requests.get(url)
    if response.status_code == 200:
        return response.json()
    else:
        return {'error_message': 'Failed to fetch nearby services.', 'results': []}

"""function to benchmark performance"""

def benchmark_performance(actual_location, obfuscated_location, cloaked_areas, geofence_center, geofence_radius):
    # Privacy metrics
    privacy_distance = geodesic(actual_location, obfuscated_location).meters
    cloaking_entropy = len(cloaked_areas)

    # Usability metrics
    usability_distance = geodesic(actual_location, geofence_center).meters
    within_geofence = check_geofence(actual_location, geofence_center, geofence_radius)

    # Benchmark against existing methods (example values)
    existing_method_privacy_distance = 1000  # Example value
    existing_method_usability_distance = 500  # Example value

    return {
        "privacy_distance": privacy_distance,
        "cloaking_entropy": cloaking_entropy,
        "usability_distance": usability_distance,
        "within_geofence": within_geofence,
        "existing_method_privacy_distance": existing_method_privacy_distance,
        "existing_method_usability_distance": existing_method_usability_distance
    }

"""function to encrypt location data"""

def encrypt_location_data(location, key):
    # Convert location to string and encrypt
    location_str = f"{location[0]},{location[1]}"
    fernet = Fernet(key)
    encrypted_location = fernet.encrypt(location_str.encode())
    return encrypted_location

def decrypt_location_data(encrypted_location, key):
    # Decrypt location data
    fernet = Fernet(key)
    decrypted_location = fernet.decrypt(encrypted_location).decode()
    lat, lon = map(float, decrypted_location.split(','))
    return (lat, lon)

"""EXAMPLE USAGE"""

# Example usage with Chennai coordinates
actual_location = (13.0827, 80.2707)  # Chennai coordinates
radius = 0.5  # 500 meters
user_locations = [(13.0827, 80.2707), (13.0838, 80.2710), (13.0848, 80.2720), (13.0858, 80.2730)]
base_k = 2

# Example population data (lat, lon): density
population_data = {
    (13.0827, 80.2707): 5000,  # Chennai
    (13.0838, 80.2710): 4500,
    (13.0848, 80.2720): 4000,
    (13.0858, 80.2730): 3500,
}

# Generate cloaked areas using density-based clustering
cloaked_areas = density_based_cloaking(user_locations, base_k, radius)
print("Density-based Cloaked Areas:", cloaked_areas)

# Generate cloaked areas using adaptive k-anonymity
cloaked_areas_adaptive = adaptive_k_anonymity(user_locations, base_k, radius, population_data)
print("Adaptive k-anonymity Cloaked Areas:", cloaked_areas_adaptive)

# Visualize cloaked area
cloaked_location = generate_cloaked_area_haversine(actual_location, radius)
map_cloaked_area = visualize_cloaked_area(actual_location, cloaked_location, radius)
map_cloaked_area.save('cloaked_area_map.html')
map_cloaked_area

# Geofence center and parameters
geofence_center = (13.0827, 80.2707)  # Chennai
base_radius = 500  # 500 meters
user_privacy_level = 1.5  # Example privacy level
user_location = (13.0838, 80.2710)  # Example user location in Chennai

# Check fuzzy geofence
if fuzzy_geofence(user_location, geofence_center, base_radius, user_privacy_level):
    print("User is inside the fuzzy geofence.")
else:
    print("User is outside the fuzzy geofence.")

# Visualize geofence
visualize_geofence(user_location, geofence_center, base_radius * user_privacy_level)

# Add differential privacy noise
sensitivity = 0.05  # Example sensitivity value
obfuscated_location = adaptive_differential_privacy_noise(actual_location, sensitivity)
print("Obfuscated Location with Adaptive Differential Privacy:", obfuscated_location)

# Evaluate adversarial robustness
robustness = evaluate_adversarial_robustness(actual_location, obfuscated_location)
print("Adversarial Robustness:", robustness)

# Fetch nearby services
api_key = "YOUR_GOOGLE_MAPS_API_KEY"
nearby_services = fetch_nearby_services(obfuscated_location, api_key)
print("Nearby Services:", nearby_services)

# Benchmark performance
metrics = benchmark_performance(actual_location, obfuscated_location, cloaked_areas, geofence_center, base_radius)
print("Performance Benchmarking Metrics:", metrics)

# Encrypt location data
key = Fernet.generate_key()
encrypted_location = encrypt_location_data(actual_location, key)
print("Encrypted Location:", encrypted_location)

# Decrypt location data
decrypted_location = decrypt_location_data(encrypted_location, key)
print("Decrypted Location:", decrypted_location)